"use client";

import Link from "next/link";
import { ArrowRight, Check, CircleHelp, Mail, PhoneCall, Settings2, ShieldCheck } from "lucide-react";
import { MarketingFooter } from "@/components/marketing-footer";
import { MarketingHeader } from "@/components/marketing-header";
import { useI18n } from "@/i18n/locale-provider";
import { marketingCopy } from "@/i18n/marketing-copy";

export default function PricingPage() {
  const { locale } = useI18n();
  const c = marketingCopy[locale].pricing;
  const emailHref = locale === "zh" ? "mailto:support@visutry.com?subject=Runory%20%E5%95%86%E4%B8%9A%E5%92%A8%E8%AF%A2&body=%E5%85%AC%E5%8F%B8%EF%BC%9A%0A%E6%9C%8D%E5%8A%A1%E8%A1%8C%E4%B8%9A%EF%BC%9A%0A%E4%BC%98%E5%85%88%E6%B5%81%E7%A8%8B%EF%BC%9A%0A%E5%9B%A2%E9%98%9F%E8%A7%84%E6%A8%A1%EF%BC%9A%0A%E9%A2%84%E6%9C%9F%E6%97%B6%E9%97%B4%EF%BC%9A" : "mailto:support@visutry.com?subject=Runory%20Commercial%20Inquiry&body=Company%3A%0AService%20industry%3A%0APriority%20workflow%3A%0ATeam%20size%3A%0AExpected%20timeline%3A";
  const layerIcons = [ShieldCheck, Settings2, PhoneCall];
  const faqLabel = locale === "zh" ? "常见问题" : "FAQ";

  return <main className="min-h-screen bg-[#fbf8f1] text-neutral-950"><MarketingHeader />
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 sm:py-20 lg:px-10 lg:py-28"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{c.eyebrow}</p><h1 className="mt-6 max-w-4xl font-serif text-5xl leading-[1.02] tracking-[-.045em] sm:text-7xl">{c.title}</h1><p className="mt-8 max-w-3xl text-lg leading-8 text-neutral-600">{c.subtitle}</p></section>
    <section className="border-y border-black/10 bg-white py-16 sm:py-20"><div className="mx-auto grid max-w-7xl gap-5 px-5 sm:px-6 md:grid-cols-2 lg:px-10 xl:grid-cols-4">{c.plans.map(([name, price, minutes, audience, features], index) => { const isPopular = index === 1; const isCustom = index === 3; return <article key={name} className={`relative flex h-full flex-col rounded-[24px] border p-6 sm:p-7 ${isPopular ? "border-orange-500 bg-neutral-950 text-white shadow-[0_24px_70px_rgba(50,35,20,.14)]" : "border-black/10 bg-[#fbf8f1]"}`}>{isPopular && <span className="absolute right-5 top-5 rounded-full bg-orange-600 px-3 py-1 text-xs font-semibold text-white">{c.popular}</span>}<h2 className="text-xl font-semibold">{name}</h2><div className="mt-6"><span className="font-serif text-5xl tracking-[-.04em]">{price}</span>{!isCustom && <span className={isPopular ? "text-neutral-400" : "text-neutral-500"}> {c.monthly}</span>}</div><p className={`mt-3 text-sm ${isPopular ? "text-orange-300" : "text-orange-600"}`}>{isCustom ? minutes : `${minutes} ${c.included}`}</p><p className={`mt-5 text-sm leading-6 ${isPopular ? "text-neutral-300" : "text-neutral-600"}`}>{audience}</p><div className={`mt-6 flex-1 border-t pt-5 ${isPopular ? "border-white/10" : "border-black/10"}`}>{features.map((feature) => <div key={feature} className={`mt-3 flex gap-2.5 text-sm ${isPopular ? "text-neutral-200" : "text-neutral-700"}`}><Check size={16} className="mt-0.5 shrink-0 text-orange-500" />{feature}</div>)}</div><Link href={emailHref} className={`mt-7 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-full px-5 text-sm font-semibold ${isPopular ? "bg-orange-600 text-white" : "bg-neutral-950 text-white"}`}>{c.contact} <ArrowRight size={16} /></Link></article>; })}</div></section>
    <section className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><div className="max-w-4xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{c.layersEyebrow}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em] sm:text-5xl">{c.layersTitle}</h2></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{c.layers.map(([title, body], i) => { const Icon = layerIcons[i]; return <article key={title} className="rounded-2xl border border-black/10 bg-white p-6"><Icon size={22} className="text-orange-600" /><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-neutral-600">{body}</p></article>; })}</div></div></section>
    <section className="bg-neutral-950 py-16 text-white"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 px-5 sm:px-6 md:flex-row md:items-center lg:px-10"><h2 className="max-w-3xl font-serif text-4xl tracking-[-.035em]">{c.cta}</h2><Link href={emailHref} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-orange-600 px-7 font-semibold text-white">{c.contact} <Mail size={18} /></Link></div></section>
    <section className="py-20 sm:py-24"><div className="mx-auto max-w-4xl px-5 sm:px-6 lg:px-10"><div className="flex items-center gap-2 text-orange-600"><CircleHelp size={19} /><span className="text-sm font-semibold uppercase tracking-[.18em]">{faqLabel}</span></div><h2 className="mt-4 font-serif text-4xl tracking-[-.035em]">{c.faqTitle}</h2><div className="mt-10 divide-y divide-black/10 border-y border-black/10">{c.faqs.map(([question, answer]) => <article key={question} className="py-6"><h3 className="font-semibold">{question}</h3><p className="mt-2 text-sm leading-7 text-neutral-600">{answer}</p></article>)}</div></div></section>
    <MarketingFooter /></main>;
}
