"use client";

import Link from "next/link";
import { ArrowRight, Check, CircleHelp, Mail, PhoneCall, Settings2, ShieldCheck } from "lucide-react";
import { MarketingFooter } from "@/components/marketing-footer";
import { MarketingHeader } from "@/components/marketing-header";
import { useI18n } from "@/i18n/locale-provider";
import { marketingCopy } from "@/i18n/marketing-copy";

export default function PricingPage() {
  const { locale } = useI18n();
  const c = marketingCopy[locale].pricing;
  const zh = locale === "zh";
  const emailHref = zh ? "mailto:support@visutry.com?subject=Runory%20%E5%95%86%E4%B8%9A%E5%92%A8%E8%AF%A2&body=%E5%85%AC%E5%8F%B8%EF%BC%9A%0A%E6%9C%8D%E5%8A%A1%E8%A1%8C%E4%B8%9A%EF%BC%9A%0A%E4%BC%98%E5%85%88%E6%B5%81%E7%A8%8B%EF%BC%9A%0A%E5%9B%A2%E9%98%9F%E8%A7%84%E6%A8%A1%EF%BC%9A%0A%E9%A2%84%E6%9C%9F%E6%97%B6%E9%97%B4%EF%BC%9A" : "mailto:support@visutry.com?subject=Runory%20Commercial%20Inquiry&body=Company%3A%0AService%20industry%3A%0APriority%20workflow%3A%0ATeam%20size%3A%0AExpected%20timeline%3A";
  const layerIcons = [ShieldCheck, Settings2, PhoneCall];
  const faqLabel = zh ? "常见问题" : "FAQ";
  const fit = zh ? [["Starter", "适合单一团队验证语音接单与基础运营闭环。", "优先解决一条高频流程，保持配置和集成范围精简。"], ["Growth", "适合已有稳定业务量、需要完整 CRM + Sales + FSM 协同的成长型服务企业。", "支持更高使用量、更多自动化和更完整的运营报表。"], ["Pro", "适合多团队、多区域或多服务线的复杂运营。", "用于更复杂的流程、权限、容量和支持要求。"], ["Enterprise", "适合需要企业集成、定制 SLA 或特殊部署方式的组织。", "商业条款、实施方式和运行边界按项目明确。"]] : [["Starter", "For one team validating voice intake and a foundational operating loop.", "Best when one high-frequency workflow is prioritized and integrations remain intentionally limited."], ["Growth", "For growing service businesses that need a connected CRM + Sales + FSM operation.", "Adds higher volume, more automation, and broader operational reporting."], ["Pro", "For multi-team, multi-location, or multi-service operations.", "Designed for more complex workflows, permissions, capacity, and support needs."], ["Enterprise", "For organizations requiring enterprise integrations, custom SLA, or deployment options.", "Commercial terms, implementation, and operating boundaries are scoped explicitly."]];
  const expansion = zh ? [["先上线核心闭环", "从接单、销售、排期或现场执行中的一个关键环节开始。"], ["验证业务指标", "确认响应时间、管理工作量、流程可见性与完成度得到改善。"], ["扩展 Pack 与自动化", "在已有业务对象和权限模型上增加更多流程，而不是重新建设系统。"]] : [["Launch the core loop", "Start with one priority point in intake, sales, scheduling, or field execution."], ["Validate operating metrics", "Confirm improvements in response time, admin effort, visibility, and completion."], ["Expand Packs and automation", "Add more workflows on the existing business objects and permission model instead of rebuilding."]];

  return <main className="min-h-screen bg-[#fbf8f1] text-neutral-950"><MarketingHeader />
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 sm:py-20 lg:px-10 lg:py-28"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{c.eyebrow}</p><h1 className="mt-6 max-w-4xl font-serif text-5xl leading-[1.02] tracking-[-.045em] sm:text-7xl">{c.title}</h1><p className="mt-8 max-w-3xl text-lg leading-8 text-neutral-600">{c.subtitle}</p><div className="mt-8 flex flex-wrap gap-3"><Link href="#plans" className="inline-flex items-center gap-2 rounded-full bg-neutral-950 px-6 py-3 font-semibold text-white">{zh ? "查看方案" : "View plans"}<ArrowRight size={18}/></Link><Link href="/pilot" className="inline-flex items-center rounded-full border border-black/15 bg-white px-6 py-3 font-semibold">{zh ? "先做试点" : "Start with a pilot"}</Link></div></section>
    <section id="plans" className="border-y border-black/10 bg-white py-16 sm:py-20"><div className="mx-auto grid max-w-7xl gap-5 px-5 sm:px-6 md:grid-cols-2 lg:px-10 xl:grid-cols-4">{c.plans.map(([name, price, minutes, audience, features], index) => { const isPopular = index === 1; const isCustom = index === 3; return <article key={name} className={`relative flex h-full flex-col rounded-[24px] border p-6 sm:p-7 ${isPopular ? "border-orange-500 bg-neutral-950 text-white shadow-[0_24px_70px_rgba(50,35,20,.14)]" : "border-black/10 bg-[#fbf8f1]"}`}>{isPopular && <span className="absolute right-5 top-5 rounded-full bg-orange-600 px-3 py-1 text-xs font-semibold text-white">{c.popular}</span>}<h2 className="text-xl font-semibold">{name}</h2><div className="mt-6"><span className="font-serif text-5xl tracking-[-.04em]">{price}</span>{!isCustom && <span className={isPopular ? "text-neutral-400" : "text-neutral-500"}> {c.monthly}</span>}</div><p className={`mt-3 text-sm ${isPopular ? "text-orange-300" : "text-orange-600"}`}>{isCustom ? minutes : `${minutes} ${c.included}`}</p><p className={`mt-5 text-sm leading-6 ${isPopular ? "text-neutral-300" : "text-neutral-600"}`}>{audience}</p><div className={`mt-6 flex-1 border-t pt-5 ${isPopular ? "border-white/10" : "border-black/10"}`}>{features.map((feature) => <div key={feature} className={`mt-3 flex gap-2.5 text-sm ${isPopular ? "text-neutral-200" : "text-neutral-700"}`}><Check size={16} className="mt-0.5 shrink-0 text-orange-500" />{feature}</div>)}</div><Link href={emailHref} className={`mt-7 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-full px-5 text-sm font-semibold ${isPopular ? "bg-orange-600 text-white" : "bg-neutral-950 text-white"}`}>{c.contact} <ArrowRight size={16} /></Link></article>; })}</div></section>
    <section className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "选择建议" : "Plan fit"}</p><h2 className="mt-4 max-w-4xl font-serif text-4xl tracking-[-.035em] sm:text-5xl">{zh ? "根据运营复杂度选择，而不只是根据通话分钟数。" : "Choose by operating complexity—not only by included minutes."}</h2><div className="mt-10 grid gap-5 md:grid-cols-2">{fit.map(([name, title, body]) => <article key={name} className="rounded-2xl border border-black/10 bg-white p-6"><p className="text-sm font-semibold text-orange-600">{name}</p><h3 className="mt-3 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-neutral-600">{body}</p></article>)}</div></div></section>
    <section className="border-y border-black/10 bg-[#f4efe5] py-20"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><div className="max-w-4xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{c.layersEyebrow}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em] sm:text-5xl">{c.layersTitle}</h2></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{c.layers.map(([title, body], i) => { const Icon = layerIcons[i]; return <article key={title} className="rounded-2xl border border-black/10 bg-white p-6"><Icon size={22} className="text-orange-600" /><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-neutral-600">{body}</p></article>; })}</div></div></section>
    <section className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "扩展路径" : "Expansion path"}</p><h2 className="mt-4 max-w-4xl font-serif text-4xl tracking-[-.035em] sm:text-5xl">{zh ? "价格随业务价值和运营范围扩展，而不是一次性建设大系统。" : "Commercial scope expands with proven operating value—not through a large upfront transformation."}</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{expansion.map(([title, body], index) => <article key={title} className="rounded-2xl border border-black/10 bg-white p-6"><span className="text-xs font-semibold text-orange-600">0{index + 1}</span><h3 className="mt-6 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-neutral-600">{body}</p></article>)}</div></div></section>
    <section className="bg-neutral-950 py-16 text-white"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 px-5 sm:px-6 md:flex-row md:items-center lg:px-10"><h2 className="max-w-3xl font-serif text-4xl tracking-[-.035em]">{c.cta}</h2><Link href={emailHref} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-orange-600 px-7 font-semibold text-white">{c.contact} <Mail size={18} /></Link></div></section>
    <section className="py-20 sm:py-24"><div className="mx-auto max-w-4xl px-5 sm:px-6 lg:px-10"><div className="flex items-center gap-2 text-orange-600"><CircleHelp size={19} /><span className="text-sm font-semibold uppercase tracking-[.18em]">{faqLabel}</span></div><h2 className="mt-4 font-serif text-4xl tracking-[-.035em]">{c.faqTitle}</h2><div className="mt-10 divide-y divide-black/10 border-y border-black/10">{c.faqs.map(([question, answer]) => <article key={question} className="py-6"><h3 className="font-semibold">{question}</h3><p className="mt-2 text-sm leading-7 text-neutral-600">{answer}</p></article>)}</div></div></section>
    <MarketingFooter /></main>;
}