import { z } from "zod";

// ── Field Types ──
export const fieldTypes = ["text", "email", "phone", "number", "date", "select", "boolean"] as const;
export type FieldType = (typeof fieldTypes)[number];

// ── Module Manifest ──
export const fieldDefinitionSchema = z.object({
  key: z.string(),
  label: z.string(),
  type: z.enum(fieldTypes),
  ownership: z.enum(["module_owned", "workspace_extension"]).default("module_owned"),
  required: z.boolean().default(false),
  default_value: z.string().optional(),
  validation: z.record(z.unknown()).optional(),
});

export const viewConfigSchema = z.object({
  columns: z.array(z.object({
    field: z.string(),
    label: z.string().optional(),
  })).optional(),
  sections: z.array(z.object({
    title: z.string(),
    fields: z.array(z.object({
      field: z.string(),
      required: z.boolean().optional(),
    })),
  })).optional(),
  actions: z.array(z.string()).optional(),
  pageSize: z.number().optional(),
}).passthrough();

export const viewDefinitionSchema = z.object({
  object: z.string(),
  key: z.string(),
  type: z.enum(["list", "form"]),
  label: z.string(),
  config: viewConfigSchema,
});

export const objectDefinitionSchema = z.object({
  key: z.string(),
  label: z.string(),
  fields: z.array(fieldDefinitionSchema),
});

export const extensionPointSchema = z.object({
  entities: z.array(z.object({
    entity: z.string(),
    customFields: z.object({
      enabled: z.boolean(),
      allowedTypes: z.array(z.string()),
      maxFields: z.number().optional(),
      reservedKeys: z.array(z.string()),
    }).optional(),
    customRelations: z.object({
      enabled: z.boolean(),
    }).optional(),
  })).optional(),
  views: z.array(z.object({
    view: z.string(),
    slots: z.array(z.object({
      id: z.string(),
      type: z.string(),
      allowedExtensions: z.array(z.string()),
      risk: z.string().default("low"),
    })),
  })).optional(),
});

export const moduleManifestSchema = z.object({
  id: z.string(),
  name: z.string(),
  version: z.string(),
  coreCompatibility: z.string(),
  dependencies: z.array(z.string()).optional(),
  objects: z.array(objectDefinitionSchema),
  views: z.array(viewDefinitionSchema),
  permissions: z.array(z.string()).optional(),
  migrations: z.object({
    install: z.string(),
    uninstallPolicy: z.string().default("retain_data"),
  }),
  ui: z.object({
    navigation: z.array(z.object({
      label: z.string(),
      route: z.string(),
      icon: z.string().default("file"),
      sortOrder: z.number().default(100),
    })).optional(),
  }).optional(),
  extensionPoints: extensionPointSchema.optional(),
  upgradePolicy: z.object({
    supportsWorkspaceExtensions: z.boolean().default(true),
    breakingChangePolicy: z.string().default("manual_review"),
  }).optional(),
});

export type ModuleManifest = z.infer<typeof moduleManifestSchema>;

// ── Pack Manifest ──
export const packManifestSchema = z.object({
  id: z.string(),
  name: z.string(),
  version: z.string(),
  coreCompatibility: z.string(),
  modules: z.array(z.string()),
  defaultTemplate: z.string().optional(),
  marketplace: z.object({
    category: z.string(),
    license: z.string(),
    publisher: z.string(),
  }).optional(),
});

export type PackManifest = z.infer<typeof packManifestSchema>;

// ── Template Manifest ──
export const templateManifestSchema = z.object({
  id: z.string(),
  name: z.string(),
  version: z.string(),
  terminology: z.record(z.string()).optional(),
  navigation: z.array(z.string()).optional(),
  homepage: z.object({
    layout: z.string(),
    widgets: z.array(z.string()),
  }).optional(),
  roleEntry: z.record(z.string()).optional(),
});

export type TemplateManifest = z.infer<typeof templateManifestSchema>;

// ── Extension Plan (generated by Personal Agent, validated by Runory) ──
export const customFieldPlanSchema = z.object({
  targetObject: z.string(),
  fieldKey: z.string(),
  label: z.string(),
  type: z.enum(fieldTypes),
  ownership: z.literal("workspace_extension"),
  required: z.boolean().default(false),
  validation: z.record(z.unknown()).optional(),
  ui: z.object({
    listColumn: z.boolean().default(false),
    slot: z.string().optional(),
    order: z.number().default(100),
  }).optional(),
});

export const extensionPlanSchema = z.object({
  name: z.string(),
  description: z.string().optional(),
  targetModules: z.array(z.string()),
  riskLevel: z.enum(["low", "medium", "high"]).default("low"),
  customFields: z.array(customFieldPlanSchema),
});

export type ExtensionPlan = z.infer<typeof extensionPlanSchema>;
export type CustomFieldPlan = z.infer<typeof customFieldPlanSchema>;

// ── API Response Types ──
export interface ToolEnvelope<T> {
  success: boolean;
  data?: T;
  error?: { code: string; message: string };
}

export function ok<T>(data: T): ToolEnvelope<T> {
  return { success: true, data };
}

export function err(code: string, message: string): ToolEnvelope<never> {
  return { success: false, error: { code, message } };
}
