"use client";

import { ArrowRight, CheckCircle2, Mail } from "lucide-react";
import Link from "next/link";
import { MarketingFooter } from "@/components/marketing-footer";
import { MarketingHeader } from "@/components/marketing-header";
import { useI18n } from "@/i18n/locale-provider";
import { marketingCopy } from "@/i18n/marketing-copy";

export default function PilotPage() {
  const { locale } = useI18n();
  const c = marketingCopy[locale].pilot;
  const zh = locale === "zh";
  const emailHref = locale === "zh" ? "mailto:support@visutry.com?subject=Runory%20%E8%AF%95%E7%82%B9%E7%94%B3%E8%AF%B7&body=%E5%85%AC%E5%8F%B8%EF%BC%9A%0A%E8%A1%8C%E4%B8%9A%EF%BC%9A%0A%E4%BC%98%E5%85%88%E6%B5%81%E7%A8%8B%EF%BC%9A%0A%E5%9B%A2%E9%98%9F%E8%A7%84%E6%A8%A1%EF%BC%9A%0A%E7%9B%AE%E6%A0%87%E6%8C%87%E6%A0%87%EF%BC%9A" : "mailto:support@visutry.com?subject=Runory%20Pilot%20Request&body=Company%3A%0AIndustry%3A%0APriority%20workflow%3A%0ATeam%20size%3A%0ASuccess%20metric%3A";
  const path = zh ? [["01", "明确流程", "选择一条可重复、可衡量、边界清晰的 CRM、销售、接单或 FSM 流程。"], ["02", "配置运行模型", "确认角色、字段、表单、业务规则、状态和必要的外部集成。"], ["03", "导入样本数据", "使用有限但真实的数据验证客户、工单、报价、排期和执行记录。"], ["04", "上线并衡量", "由真实团队使用，记录响应速度、人工工作量、流程可见性和完成纪律。"]] : [["01", "Define the workflow", "Choose one repeatable, measurable CRM, Sales, Intake, or FSM process with clear boundaries."], ["02", "Configure the runtime", "Confirm roles, fields, forms, business rules, states, and only the integrations needed for the first loop."], ["03", "Load representative data", "Use limited but real records to validate customers, work, quotes, schedules, and execution history."], ["04", "Go live and measure", "Run the workflow with a real team and measure response, admin effort, visibility, and completion discipline."]];
  const measures = zh ? [["响应时间", "从客户需求进入到首次有效处理的时间。"], ["人工工作量", "重复录入、协调、提醒和状态更新减少多少。"], ["流程可见性", "负责人能否清楚看到每个任务当前状态与下一步。"], ["业务完成度", "报价、排期、执行、收款或跟进是否更稳定地完成。"]] : [["Response time", "Time from customer demand entering the system to the first effective action."], ["Administrative effort", "Reduction in duplicate entry, coordination, reminders, and status maintenance."], ["Process visibility", "Whether owners can clearly see current state, responsibility, and next action."], ["Completion discipline", "Whether quotes, schedules, execution, payment, or follow-up complete more consistently."]];

  return <main className="min-h-screen bg-[#fbf8f1] text-neutral-950"><MarketingHeader />
    <section className="mx-auto grid max-w-7xl gap-12 px-6 py-16 lg:grid-cols-[.86fr_1.14fr] lg:px-10 lg:py-24"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{c.eyebrow}</p><h1 className="mt-6 max-w-4xl font-serif text-5xl leading-[1.02] tracking-[-.045em] sm:text-7xl">{c.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-neutral-600">{c.subtitle}</p><div className="mt-10 space-y-4">{c.bullets.map((item) => <div key={item} className="flex items-center gap-3 text-sm font-medium text-neutral-700"><CheckCircle2 size={18} className="text-orange-600" />{item}</div>)}</div></div><div className="rounded-[28px] border border-black/10 bg-white p-8 shadow-[0_24px_70px_rgba(50,35,20,.08)] sm:p-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "申请试点" : "Request a pilot"}</p><h2 className="mt-5 font-serif text-3xl tracking-[-.03em]">{zh ? "告诉我们最值得先解决的一条流程。" : "Tell us the first workflow worth fixing."}</h2><p className="mt-4 max-w-lg leading-7 text-neutral-600">{zh ? "提供行业、团队规模、当前流程和希望改善的指标。我们会判断适配度，并给出明确的首期范围。" : "Share your industry, team size, current process, and the metric you want to improve. We will assess fit and define a practical first scope."}</p><Link href={emailHref} className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-full bg-neutral-950 px-7 font-semibold text-white">{c.email} <Mail size={18} /></Link></div></section>
    <section className="border-y border-black/10 bg-white py-16 sm:py-20"><div className="mx-auto grid max-w-7xl gap-5 px-6 md:grid-cols-2 lg:grid-cols-4 lg:px-10">{c.cards.map(([title, body], index) => <article key={title} className="rounded-2xl border border-black/10 bg-[#fbf8f1] p-6"><span className="text-xs font-semibold text-orange-600">0{index + 1}</span><h2 className="mt-8 text-lg font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-neutral-600">{body}</p></article>)}</div></section>
    <section className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-6 lg:px-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "试点执行路径" : "Pilot execution path"}</p><h2 className="mt-4 max-w-4xl font-serif text-4xl tracking-[-.035em] sm:text-5xl">{zh ? "从业务问题到真实运行，不停留在演示环境。" : "From business problem to live operation—not a sandbox demonstration."}</h2><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{path.map(([no, title, body]) => <article key={no} className="rounded-2xl border border-black/10 bg-white p-6"><span className="text-sm font-semibold text-orange-600">{no}</span><h3 className="mt-6 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-neutral-600">{body}</p></article>)}</div></div></section>
    <section className="border-y border-black/10 bg-neutral-950 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-2 lg:px-10"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-300">{zh ? "成功标准" : "Success criteria"}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em]">{zh ? "在开始之前，就明确什么叫有效。" : "Define what success means before implementation begins."}</h2></div><div className="grid gap-4 sm:grid-cols-2">{measures.map(([title, body]) => <article key={title} className="rounded-2xl border border-white/10 bg-white/5 p-5"><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-neutral-400">{body}</p></article>)}</div></div></section>
    <section className="mx-auto grid max-w-7xl gap-10 px-6 py-20 lg:grid-cols-2 lg:px-10"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{c.candidatesEyebrow}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em]">{c.candidatesTitle}</h2></div><div className="space-y-4">{c.candidates.map((item) => <div key={item} className="flex gap-3 border-b border-black/10 pb-4 text-neutral-700"><CheckCircle2 size={19} className="mt-0.5 shrink-0 text-orange-600" />{item}</div>)}</div></section>
    <section className="mx-auto max-w-7xl px-6 pb-24 lg:px-10"><div className="flex flex-col items-start justify-between gap-6 rounded-3xl bg-orange-50 p-8 sm:flex-row sm:items-center sm:p-10"><h2 className="max-w-3xl font-serif text-3xl tracking-[-.03em] sm:text-4xl">{zh ? "先证明一条流程，再扩展成完整运营系统。" : "Prove one operating loop, then expand into the wider system."}</h2><Link href={emailHref} className="inline-flex shrink-0 items-center gap-2 rounded-full bg-neutral-950 px-6 py-3 font-semibold text-white">{c.email}<ArrowRight size={18}/></Link></div></section>
    <MarketingFooter /></main>;
}