export const marketingCopy = {
  en: {
    nav: { product: "Product", solutions: "Solutions", platform: "Platform", pricing: "Pricing", resources: "Resources", pilot: "Start a Pilot", workspace: "Workspace" },
    footer: {
      pilotEyebrow: "Focused Pilot", pilotTitle: "Turn one priority workflow into a working operating loop.", pilotCta: "Start a Pilot",
      description: "The field service operating system for the Agent era. CRM, Sales, Voice Intake, and FSM in one governed runtime.", github: "GitHub repository",
      product: "Product", solutions: "Solutions", resources: "Resources", overview: "Overview", voice: "Voice & Messaging", agent: "Agent Interface", platform: "Platform", serviceBusinesses: "Service Businesses", pricing: "Pricing", focusedPilot: "Focused Pilot", security: "Security", signIn: "Sign in", insights: "Insights", docs: "Documentation", openSource: "Open Source", tagline: "Tell it. Run it."
    },
    home: {
      eyebrow: "Runory", title: "The field service operating system for the Agent era.", subtitle: "CRM, Sales, Voice Intake, and FSM unified in one adaptive operating system for service businesses.", pilot: "Start a Pilot", explore: "Explore the Product", launch: "Mature use cases can often launch in 1–2 weeks.",
      ops: "Today’s Operations", live: "Live workspace", stats: ["12 new leads", "8 visits scheduled", "3 quotes pending"], pipeline: "Service pipeline", today: "Today", pipelineItems: ["New request captured", "Site visit confirmed", "Quote awaiting approval"], agentAction: "Agent action", agentPrompt: "Schedule tomorrow’s highest-priority visits.", agentResult: "3 technicians matched · 5 visits ready for confirmation", mobile: "Mobile field work", mobileBody: "Tasks, forms, evidence, completion.", externalAgent: "External Agent interface", externalAgentBody: "Configure, operate, schedule, automate.",
      platformEyebrow: "One complete service platform", platformTitle: "From the first conversation to completed service.", journey: ["Voice & SMS Intake", "CRM Pack", "Sales Pack", "FSM Pack", "Payment & Retention"],
      outcomeEyebrow: "Business outcomes", outcomeTitle: "Less fragmentation. More completed work.", outcomes: [["Capture more demand", "Turn calls, messages, and web requests into structured leads and work."], ["Move faster", "Reduce handoffs between intake, sales, scheduling, and field execution."], ["Reduce admin work", "Let teams and Agents operate one shared business record instead of duplicate tools."], ["Keep control", "Apply permissions, validation, confirmation, and audit to every important action."]],
      agentEyebrow: "Built for the Agent era", agentTitle: "Your Agent understands the work. Runory makes it run safely.", agentCards: [["Configure", "Adapt fields, forms, roles, workflows, and reports."], ["Operate", "Create records, assign work, update status, and coordinate teams."], ["Schedule", "Run recurring checks, reminders, and conditional actions."], ["Control", "Keep every action within business rules and permissions."]],
      capabilityCards: [["Omnichannel Intake", "Phone, voice, SMS, web, and manual intake become structured business work."], ["Three Core Packs", "CRM, Sales, and FSM work together without stitching together multiple systems."], ["External Super Agents", "Use Codex, ChatGPT, Claude, Cursor, Trae, or compatible enterprise Agents."], ["Governed Execution", "Permissions, validation, confirmation, audit, and rollback where supported."]]
    },
    product: { eyebrow: "Runory Product", title: "One operating system for modern service businesses.", subtitle: "Runory combines omnichannel intake, CRM, Sales, and FSM into one adaptive platform designed to work with external Super Agents.", packs: [["CRM Pack", "Capture leads, manage customers, sites, contacts, and service history."], ["Sales Pack", "Move opportunities from qualification to quote, approval, and payment."], ["FSM Pack", "Schedule, dispatch, execute, and complete field service operations."]], cta: "Start a Pilot" },
    solutions: { eyebrow: "Solutions", title: "One operating system, adapted to how your service business actually works.", subtitle: "Start with CRM, Sales, FSM, and Omnichannel Intake. Add industry configuration without rebuilding the product.", items: [["Home Services", "Unify intake, customer records, quoting, dispatch, field work, payment, and follow-up."], ["HVAC", "Support reactive calls, maintenance plans, assets, recurring visits, and technician scheduling."], ["Plumbing", "Turn urgent calls into identified work, coordinate technicians, and keep customers informed."], ["Waterproofing & Repair", "Manage inspection, proposal, project execution, evidence, change, completion, and after-sales."], ["Installation Services", "Coordinate longer-running jobs, milestones, field teams, documents, payments, and handover."]], scenariosEyebrow: "Real operating scenarios", scenariosTitle: "Different services. The same connected operating discipline.", scenarios: [["Emergency repair", ["Customer calls", "Urgency captured", "Nearest technician", "Work completed"]], ["Inspection & quote", ["Site visit", "Evidence recorded", "Proposal approved", "Project scheduled"]], ["Recurring service", ["Plan due", "Visit created", "Customer confirmed", "Asset history updated"]]], ctaTitle: "Start with one focused workflow.", ctaBody: "Mature use cases can often launch in 1–2 weeks.", cta: "Plan a Pilot" },
    voice: { eyebrow: "Voice & Messaging", title: "Turn every customer conversation into structured business execution.", subtitle: "Runory connects phone, AI voice, SMS, web, and manual intake to CRM, Sales, and FSM workflows—without duplicate entry or disconnected call records.", cta: "Start a Pilot", steps: ["Answer", "Identify", "Capture", "Confirm", "Create Work", "Follow Up"], cards: [["Commercial-grade intake", "Capture identity, intent, service details, urgency, and preferred schedule."], ["One conversation history", "Calls, transcripts, messages, confirmations, and follow-ups stay linked to the customer and work."], ["Real business outcomes", "Create Leads, Customers, Work Orders, Visits, and follow-up tasks through governed commands."], ["Provider-safe execution", "Idempotency, confirmation, human handoff, audit, and operational visibility."]] },
    pricing: { eyebrow: "Pricing", title: "Clear plans for service operations that start at $449/month.", subtitle: "Choose a practical starting plan, then scope implementation, integrations, and third-party usage transparently.", monthly: "/month", included: "included minutes", popular: "Most popular", contact: "Contact us", plans: [["Starter", "$449", "1,000", "Small service teams", ["Voice intake", "CRM, Sales, and FSM baseline", "Scheduling and SMS", "Operational records and follow-up"]], ["Growth", "$999", "3,000", "Growing service businesses", ["Full operating loop", "Advanced reporting", "Higher automation volume", "Priority onboarding"]], ["Pro", "$2,499", "8,000", "Multi-team and multi-location operations", ["Advanced operations", "Higher usage", "Complex workflows", "Expanded support"]], ["Enterprise", "Custom", "Custom", "Complex deployments", ["Custom SLA", "Enterprise integrations", "Custom workflows", "Deployment options"]]], layersEyebrow: "Commercial structure", layersTitle: "Subscription, implementation, and provider usage stay visibly separate.", layers: [["Runory Subscription", "The selected CRM, Sales, FSM, Voice, Agent, governance, and operational capabilities."], ["Implementation", "Configuration, onboarding, migration, integration, and rollout work for the agreed scope."], ["Usage & Providers", "Telephony, SMS, AI models, payments, and premium third-party services where applicable."]], faqTitle: "Commercial questions", faqs: [["Are the published prices final?", "They are starting prices for standard scopes. Final terms may vary by workflow, integrations, deployment, support, and implementation requirements."], ["What happens when included minutes are exceeded?", "Overage pricing is defined in the commercial agreement so usage remains predictable."], ["Are third-party costs included?", "Phone numbers, call minutes, SMS, payment processing, and premium provider usage may be billed separately or passed through transparently."], ["Can we begin with a pilot?", "Yes. A focused pilot validates one operating loop before a broader production rollout."]], cta: "Discuss your plan" },
    pilot: { eyebrow: "Focused Pilot", title: "Start small. Go live fast. Prove operational value.", subtitle: "Tell us which workflow matters most. We will assess fit, scope the first operating loop, and respond with a practical pilot path.", bullets: ["No broad transformation program", "One measurable workflow first", "A working system, not a slide deck"], email: "Email Runory", cards: [["Scope", "One priority workflow and one operating team."], ["Timeline", "Mature use cases can often launch in 1–2 weeks."], ["Inputs", "Business rules, sample data, users, roles, and preferred Agent interface."], ["Success", "Measure response time, admin effort, follow-up, scheduling visibility, and completion discipline."]], candidatesEyebrow: "Good pilot candidates", candidatesTitle: "A clear process, an engaged team, and a measurable problem.", candidates: ["A repeatable CRM, Sales, or FSM workflow", "A team ready to provide rules and sample data", "Limited external integrations in the first scope", "A clear operational metric to improve"] }
  },
  zh: {
    nav: { product: "产品", solutions: "解决方案", platform: "平台", pricing: "价格", resources: "资源", pilot: "启动试点", workspace: "工作空间" },
    footer: { pilotEyebrow: "聚焦试点", pilotTitle: "把一个关键业务流程，落地为真正可运行的业务闭环。", pilotCta: "启动试点", description: "面向 Agent 时代的现场服务运营系统，将 CRM、销售、语音接单与 FSM 统一在一个受治理的运行时中。", github: "GitHub 仓库", product: "产品", solutions: "解决方案", resources: "资源", overview: "产品概览", voice: "语音与消息", agent: "Agent 接口", platform: "平台", serviceBusinesses: "服务型企业", pricing: "价格", focusedPilot: "聚焦试点", security: "安全", signIn: "登录", insights: "洞察", docs: "文档", openSource: "开源", tagline: "说出来，运行起来。" },
    home: { eyebrow: "Runory", title: "面向 Agent 时代的现场服务运营系统。", subtitle: "将 CRM、销售、语音接单与 FSM 统一在一个可适配的服务企业运营系统中。", pilot: "启动试点", explore: "了解产品", launch: "成熟场景通常可在 1–2 周内上线。", ops: "今日运营", live: "实时工作空间", stats: ["12 条新线索", "8 次已排期上门", "3 份待审批报价"], pipeline: "服务流程", today: "今天", pipelineItems: ["已接收新需求", "已确认上门", "报价待审批"], agentAction: "Agent 操作", agentPrompt: "安排明天优先级最高的上门任务。", agentResult: "已匹配 3 名技师 · 5 个任务待确认", mobile: "移动现场作业", mobileBody: "任务、表单、证据与完工。", externalAgent: "外部 Agent 接口", externalAgentBody: "配置、操作、调度与自动化。", platformEyebrow: "完整的服务运营平台", platformTitle: "从第一次客户沟通，到服务完成。", journey: ["语音与短信接单", "CRM Pack", "销售 Pack", "FSM Pack", "收款与客户留存"], outcomeEyebrow: "业务成果", outcomeTitle: "减少系统割裂，完成更多业务。", outcomes: [["承接更多需求", "将电话、消息和网页请求转化为结构化线索与工单。"], ["加快业务推进", "减少接单、销售、排期和现场执行之间的交接。"], ["减少管理工作", "团队和 Agent 使用同一份业务记录，避免重复录入。"], ["保持业务可控", "关键操作都经过权限、校验、确认与审计。"]], agentEyebrow: "为 Agent 时代而生", agentTitle: "Agent 理解业务，Runory 让业务安全运行。", agentCards: [["配置", "调整字段、表单、角色、流程和报表。"], ["运营", "创建记录、分配工作、更新状态并协同团队。"], ["调度", "运行周期检查、提醒和条件动作。"], ["治理", "确保操作遵循业务规则和权限。"]], capabilityCards: [["全渠道接单", "电话、语音、短信、网页和人工录入统一转化为业务工作。"], ["三大核心 Pack", "CRM、销售与 FSM 在一个系统中协同运行。"], ["外部超级 Agent", "支持 Codex、ChatGPT、Claude、Cursor、Trae 及兼容的企业 Agent。"], ["受治理执行", "权限、校验、确认、审计，以及在支持场景中的回滚。"]] },
    product: { eyebrow: "Runory 产品", title: "一套系统，运行现代服务型企业。", subtitle: "Runory 将全渠道接单、CRM、销售与 FSM 统一在一个可适配的平台中，并面向外部超级 Agent 设计。", packs: [["CRM Pack", "管理线索、客户、服务地址、联系人与服务历史。"], ["销售 Pack", "推动商机从资格判断到报价、审批与收款。"], ["FSM Pack", "完成排期、派工、现场执行与服务闭环。"]], cta: "启动试点" },
    solutions: { eyebrow: "解决方案", title: "一套运营系统，适配服务企业真实的工作方式。", subtitle: "从 CRM、销售、FSM 与全渠道接单开始，通过行业配置扩展能力，而不是重新开发产品。", items: [["家庭服务", "统一接单、客户档案、报价、派工、现场执行、收款与跟进。"], ["暖通空调", "支持紧急报修、维保计划、设备档案、周期服务与技师排期。"], ["管道维修", "将紧急电话转化为明确工单，协调技师并持续通知客户。"], ["防水与维修", "管理勘查、方案、项目执行、过程证据、变更、完工与售后。"], ["安装服务", "协调长周期项目、里程碑、现场团队、文档、收款与交付。"]], scenariosEyebrow: "真实业务场景", scenariosTitle: "不同服务类型，共享同一套连接、规范的运营方式。", scenarios: [["紧急维修", ["客户来电", "识别紧急程度", "匹配最近技师", "完成服务"]], ["勘查与报价", ["上门勘查", "记录现场证据", "客户批准方案", "安排项目"]], ["周期服务", ["计划到期", "创建服务任务", "客户确认", "更新设备历史"]]], ctaTitle: "从一个聚焦流程开始。", ctaBody: "成熟场景通常可在 1–2 周内上线。", cta: "规划试点" },
    voice: { eyebrow: "语音与消息", title: "把每一次客户沟通，转化为结构化业务执行。", subtitle: "Runory 将电话、AI 语音、短信、网页与人工接单连接到 CRM、销售与 FSM，避免重复录入和孤立通话记录。", cta: "启动试点", steps: ["接听", "识别", "采集", "确认", "创建工单", "持续跟进"], cards: [["商业级接单", "采集客户身份、需求意图、服务细节、紧急程度与期望时间。"], ["统一会话历史", "通话、转写、消息、确认和跟进都关联到同一客户与工单。"], ["真实业务结果", "通过受治理指令创建线索、客户、工单、上门任务与跟进事项。"], ["可靠的服务商执行", "支持幂等、确认、人工接管、审计与运营可见性。"]] },
    pricing: { eyebrow: "价格", title: "面向服务运营的清晰套餐，$449/月起。", subtitle: "选择适合的起始套餐，再透明确定实施、集成和第三方用量。", monthly: "/月", included: "包含分钟数", popular: "主推套餐", contact: "联系我们", plans: [["Starter", "$449", "1,000", "小型服务团队", ["语音接单", "CRM、销售与 FSM 基础能力", "排期与短信", "运营记录与跟进"]], ["Growth", "$999", "3,000", "成长型服务企业", ["完整业务闭环", "高级报表", "更高自动化用量", "优先上线支持"]], ["Pro", "$2,499", "8,000", "多团队、多地点运营", ["高级运营能力", "更高用量", "复杂流程", "增强支持"]], ["Enterprise", "定制", "定制", "复杂部署", ["定制 SLA", "企业集成", "定制流程", "多种部署方式"]]], layersEyebrow: "商业结构", layersTitle: "订阅、实施与服务商用量保持清晰分离。", layers: [["Runory 订阅", "选定的 CRM、销售、FSM、语音、Agent、治理与运营能力。"], ["实施服务", "针对约定范围的配置、上线、迁移、集成与推广工作。"], ["用量与服务商", "电话、短信、AI 模型、支付及其他高级第三方服务。"]], faqTitle: "商业问题", faqs: [["公开价格是最终价格吗？", "这些是标准范围的起始价格。最终价格可能因流程、集成、部署、支持和实施要求而变化。"], ["包含分钟超出后如何计费？", "超量价格会在商业协议中明确，以保证费用可预测。"], ["第三方费用是否包含？", "电话号码、通话分钟、短信、支付和高级服务商用量可能单独计费或透明转付。"], ["可以先做试点吗？", "可以。聚焦试点用于先验证一个业务闭环，再扩大到正式生产范围。"]], cta: "讨论适合的套餐" },
    pilot: { eyebrow: "聚焦试点", title: "从小范围开始，快速上线，验证运营价值。", subtitle: "告诉我们最重要的业务流程。我们将评估适配度、确定首个运营闭环，并提供务实的试点路径。", bullets: ["不做宽泛的数字化改造", "先验证一个可衡量的流程", "交付可运行系统，而不是演示文稿"], email: "邮件联系 Runory", cards: [["范围", "一个关键业务流程和一个运营团队。"], ["周期", "成熟场景通常可在 1–2 周内上线。"], ["输入", "业务规则、样例数据、用户、角色及首选 Agent 接口。"], ["成功标准", "衡量响应时间、管理工作量、跟进、排期可见性与完工规范。"]], candidatesEyebrow: "适合试点的条件", candidatesTitle: "清晰的流程、投入的团队，以及可衡量的问题。", candidates: ["可重复的 CRM、销售或 FSM 流程", "团队愿意提供规则和样例数据", "首期范围内外部集成有限", "有明确需要改善的运营指标"] }
  }
} as const;

export type MarketingLocale = keyof typeof marketingCopy;
