"use client";

import { LocaleLink } from "@/components/LocaleLink";
import { ArrowRight, Bot, CalendarClock, CheckCircle2, KeyRound, Settings2, ShieldCheck } from "lucide-react";
import { MarketingFooter } from "@/components/marketing-footer";
import { MarketingHeader } from "@/components/marketing-header";
import { useI18n } from "@/i18n/locale-provider";

export default function AgentPage() {
  const { locale } = useI18n();
  const zh = locale === "zh";
  const cards = zh ? [["配置系统", "通过 Agent 辅助调整字段、表单、角色、流程、通知与业务规则。"], ["运营业务", "以自然语言创建客户、推进商机、安排上门、派工并更新业务状态。"], ["持续自动化", "建立定时、事件驱动与条件动作，同时保持可见、可控和可审计。"]] : [["Configure the system", "Use Agent-assisted operations to adapt fields, forms, roles, workflows, notifications, and business rules."], ["Operate the business", "Use natural language to create customers, move opportunities, schedule visits, assign work, and update business state."], ["Automate continuously", "Create scheduled, event-driven, and conditional actions while execution remains visible, controlled, and auditable."]];
  const controls = zh ? [["权限边界", "Agent 只能调用已授权、已版本化的业务能力。"], ["业务校验", "每个指令都遵循字段规则、状态约束与业务策略。"], ["风险与确认", "敏感操作可以要求人工确认或进入审批路径。"], ["审计与结果", "请求、执行、结果和失败都保留可追踪记录。"]] : [["Permission boundary", "Agents can only call authorized, versioned business capabilities."], ["Business validation", "Every command follows field rules, state constraints, and business policy."], ["Risk and confirmation", "Sensitive operations can require human confirmation or approval."], ["Audit and outcomes", "Requests, execution, results, and failures remain traceable."]];
  const icons = [KeyRound, CheckCircle2, ShieldCheck, CalendarClock];

  return <main className="min-h-screen bg-[#fbf8f1] text-neutral-950"><MarketingHeader />
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 sm:py-24 lg:px-10"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-orange-600">{zh ? "Agent 接口" : "Agent Interface"}</p><h1 className="mt-6 max-w-5xl font-serif text-5xl leading-[1.02] tracking-[-0.045em] sm:text-7xl">{zh ? "让外部超级 Agent 直接操作业务，而不是停留在建议层。" : "Let external Super Agents operate the business, not stop at recommendations."}</h1><p className="mt-8 max-w-3xl text-lg leading-8 text-neutral-600">{zh ? "Runory 不替代 ChatGPT、Claude、Codex 或企业 Agent。它提供确定的业务模型、受治理指令和持续运营状态，让这些 Agent 可以安全地配置和运行服务型企业。" : "Runory does not replace ChatGPT, Claude, Codex, or enterprise Agents. It provides deterministic business models, governed commands, and persistent operational state so those Agents can configure and run service businesses safely."}</p><div className="mt-10 flex flex-wrap gap-3"><LocaleLink href="/pilot" className="inline-flex items-center gap-2 rounded-full bg-neutral-950 px-6 py-3 font-semibold text-white">{zh ? "启动 Agent 试点" : "Start an Agent Pilot"}<ArrowRight size={18}/></LocaleLink><LocaleLink href="/platform" className="inline-flex rounded-full border border-black/15 bg-white px-6 py-3 font-semibold">{zh ? "查看运行时" : "Explore the Runtime"}</LocaleLink></div></section>

    <section className="border-y border-black/10 bg-white py-20"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "Agent 操作路径" : "Agent operating path"}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em] sm:text-5xl">{zh ? "理解意图、发现能力、调用指令、返回业务结果。" : "Understand intent, discover capabilities, call commands, and return business outcomes."}</h2></div><div className="mt-12 grid gap-3 md:grid-cols-5">{(zh?["业务意图","外部 Agent","MCP / Skills / SDK","Runory Runtime","业务结果"]:["Business intent","External Agent","MCP / Skills / SDK","Runory Runtime","Business outcome"]).map((item,index)=><div key={item} className={`rounded-2xl border p-5 ${index===3?"border-orange-300 bg-orange-50":"border-black/10 bg-[#fbf8f1]"}`}><span className="text-xs font-semibold text-orange-600">0{index+1}</span><p className="mt-7 font-semibold">{item}</p></div>)}</div></div></section>

    <section className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><div className="grid gap-6 md:grid-cols-3">{cards.map(([title,body],i)=>{const Icon=[Settings2,Bot,CalendarClock][i];return <article key={title} className="rounded-3xl border border-black/10 bg-white p-7"><Icon size={22} className="text-orange-600"/><h2 className="mt-5 text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-neutral-600">{body}</p></article>})}</div></div></section>

    <section className="bg-neutral-950 py-20 text-white sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-300">{zh ? "受治理执行" : "Governed execution"}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em] sm:text-5xl">{zh ? "Agent 提供智能，Runory 决定什么可以执行。" : "Agents provide intelligence. Runory decides what can execute."}</h2></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{controls.map(([title,body],i)=>{const Icon=icons[i];return <article key={title} className="rounded-2xl border border-white/10 bg-white/5 p-6"><Icon size={22} className="text-orange-300"/><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-neutral-400">{body}</p></article>})}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-6 sm:py-24 lg:px-10"><div className="rounded-[28px] border border-black/10 bg-white p-8 sm:p-12"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "适合的首个场景" : "Good first use cases"}</p><h2 className="mt-4 max-w-3xl font-serif text-4xl tracking-[-.035em]">{zh ? "从一个重复、明确、可衡量的 Agent 工作流开始。" : "Start with one repetitive, explicit, and measurable Agent workflow."}</h2><div className="mt-8 grid gap-3 md:grid-cols-2">{(zh?["未接来电自动识别、建档并跟进","报价超过 24 小时未接受时自动提醒","根据技能、区域与时间安排技师","每天汇总异常、风险与待确认事项"]:["Identify missed calls, create records, and follow up","Follow up on quotes not accepted within 24 hours","Schedule technicians by skill, territory, and availability","Summarize exceptions, risks, and pending confirmations daily"]).map(item=><div key={item} className="flex gap-3 rounded-2xl bg-[#fbf8f1] p-4"><CheckCircle2 size={19} className="mt-0.5 shrink-0 text-orange-600"/><span className="leading-6">{item}</span></div>)}</div></div></section>
    <MarketingFooter />
  </main>;
}