"use client";

import Link from "next/link";
import { ArrowRight, ClipboardCheck, MessageSquareText, PhoneCall, ShieldCheck, UserRoundCheck, Workflow } from "lucide-react";
import { MarketingFooter } from "@/components/marketing-footer";
import { MarketingHeader } from "@/components/marketing-header";
import { useI18n } from "@/i18n/locale-provider";
import { marketingCopy } from "@/i18n/marketing-copy";

export default function VoicePage() {
  const { locale } = useI18n();
  const c = marketingCopy[locale].voice;
  const zh = locale === "zh";
  const icons = [PhoneCall, MessageSquareText, Workflow, ShieldCheck];
  const architecture = zh
    ? [
        ["客户来电", "客户拨打真实业务号码，进入 PSTN 电话网络。"],
        ["Twilio", "提供真实电话号码、PSTN 接入，并通过 SIP 将通话路由给 Retell。"],
        ["Retell AI", "负责实时语音识别、自然对话、中断处理与 Tool Calling。"],
        ["Runory", "匹配客户，创建工单与预约，并触发确认、跟进和人工接管。"],
      ]
    : [
        ["Customer call", "A customer calls a real business number through the PSTN."],
        ["Twilio", "Provides the phone number, PSTN connectivity, and SIP routing to Retell."],
        ["Retell AI", "Handles real-time speech, dialogue, interruption, and tool calling."],
        ["Runory", "Matches the customer, creates work and appointments, and starts follow-up."],
      ];
  const callFlow = zh
    ? ["识别客户与服务地址", "理解问题与紧急程度", "确认预约时间", "复述关键字段", "创建工单", "创建预约", "发送确认", "触发后续跟进"]
    : ["Identify customer and site", "Understand issue and urgency", "Confirm appointment time", "Read back critical fields", "Create work order", "Create appointment", "Send confirmation", "Trigger follow-up"];
  const outcomes = zh
    ? [["识别客户与意图", "关联已有客户、服务地址、设备与历史记录，减少重复建档。"], ["结构化采集", "提取服务类型、问题描述、紧急程度、时间偏好与关键业务字段。"], ["生成业务动作", "创建线索、客户、工单、上门任务、跟进事项或人工接管任务。"], ["持续跟进", "发送确认、提醒、状态通知，并将每次沟通写回同一业务记录。"]]
    : [["Identify customer and intent", "Match existing customers, sites, assets, and history to reduce duplicate records."], ["Capture structured details", "Extract service type, problem, urgency, preferred time, and required business fields."], ["Create business actions", "Create leads, customers, work orders, visits, follow-up tasks, or human handoff tasks."], ["Continue the follow-up", "Send confirmations, reminders, and status updates while every interaction returns to the same record."]];
  const controls = zh ? [["确认与复述", "关键地址、时间、价格与承诺在创建业务动作前进行确认。"], ["幂等与去重", "重复呼叫、重试和服务商回调不会生成重复工单。"], ["人工接管", "低置信度、投诉、敏感或超出范围的对话即时转人工。"], ["审计与可见性", "录音、转写、提取字段、指令与结果保持关联和可追踪。"]] : [["Confirmation and read-back", "Critical addresses, times, prices, and commitments are confirmed before business actions are created."], ["Idempotency and deduplication", "Repeated calls, retries, and provider callbacks do not create duplicate work."], ["Human handoff", "Low-confidence, sensitive, complaint, or out-of-scope conversations transfer to a person."], ["Audit and visibility", "Recordings, transcripts, extracted fields, commands, and outcomes remain linked and traceable."]];

  return <main className="min-h-screen bg-[#fbf8f1] text-neutral-950"><MarketingHeader />
    <section className="mx-auto max-w-7xl px-5 py-14 sm:px-6 sm:py-24 lg:px-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{c.eyebrow}</p><h1 className="mt-6 max-w-5xl font-serif text-4xl leading-[1.04] tracking-[-.04em] sm:text-7xl sm:leading-[1.02]">{c.title}</h1><p className="mt-7 max-w-3xl text-base leading-7 text-neutral-600 sm:mt-8 sm:text-lg sm:leading-8">{c.subtitle}</p><div className="mt-9 flex flex-wrap gap-3 sm:mt-10"><Link href="/pilot" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-neutral-950 px-6 font-semibold text-white">{c.cta}<ArrowRight size={18}/></Link><Link href="#architecture" className="inline-flex min-h-12 items-center rounded-full border border-black/15 bg-white px-6 font-semibold">{zh ? "查看生产架构" : "See Production Architecture"}</Link></div></section>

    <section id="architecture" className="scroll-mt-24 border-y border-black/10 bg-white py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><div className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700"><span className="size-2 rounded-full bg-emerald-500" />{zh ? "已在生产环境打通" : "Live production integration"}</div><p className="mt-6 text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "生产级语音架构" : "Production voice architecture"}</p><h2 className="mt-4 font-serif text-4xl leading-tight tracking-[-.035em] sm:text-5xl">{zh ? "真实电话，经由 Twilio 与 Retell，直接进入 Runory。" : "Real calls flow through Twilio and Retell directly into Runory."}</h2><p className="mt-5 max-w-xl leading-7 text-neutral-600">{zh ? "这不是录音转写或通话后的人工录入，而是实时电话接入、实时 AI 对话与实时业务执行。" : "This is not post-call transcription or manual data entry. It is live telephony, real-time AI conversation, and real-time business execution."}</p></div><div className="grid gap-3 sm:grid-cols-2">{architecture.map(([title,body],index)=><article key={title} className="min-h-[190px] rounded-2xl border border-black/10 bg-[#fbf8f1] p-6"><span className="text-xs font-semibold text-orange-600">0{index+1}</span><h3 className="mt-6 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-neutral-600">{body}</p></article>)}</div></div></div></section>

    <section className="py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "从电话到工单" : "From call to work order"}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em] sm:text-5xl">{zh ? "工单在通话过程中创建，而不是通话后再人工补录。" : "The work order is created during the conversation, not entered manually after the call."}</h2></div><div className="mt-10 grid gap-3 sm:mt-12 sm:grid-cols-2 lg:grid-cols-4">{callFlow.map((step,index)=><div key={step} className="flex min-h-[132px] flex-col justify-between rounded-2xl border border-black/10 bg-white p-5"><span className="text-xs font-semibold text-orange-600">0{index+1}</span><p className="mt-6 font-semibold leading-6">{step}</p></div>)}</div></div></section>

    <section className="border-y border-black/10 bg-white py-16 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "灵活的电话服务商" : "Flexible telephony"}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em] sm:text-5xl">{zh ? "当前使用 Twilio，但架构并不绑定 Twilio。" : "Twilio in production, without locking the architecture to Twilio."}</h2><p className="mt-5 max-w-xl leading-7 text-neutral-600">{zh ? "Runory 当前的生产链路采用 Twilio + Retell AI。通过标准 SIP 连接，也可根据地区、号码、成本与合规要求接入其他兼容服务商。" : "Runory currently operates with Twilio and Retell AI in production. Standards-based SIP connectivity allows other compatible providers when geography, number ownership, cost, or compliance requires it."}</p></div><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-2xl border border-black/10 bg-[#fbf8f1] p-6"><h3 className="font-semibold">{zh ? "当前生产组合" : "Current production stack"}</h3><p className="mt-3 text-sm leading-6 text-neutral-600">Twilio + Retell AI + Runory</p></article><article className="rounded-2xl border border-black/10 bg-[#fbf8f1] p-6"><h3 className="font-semibold">{zh ? "连接方式" : "Connection model"}</h3><p className="mt-3 text-sm leading-6 text-neutral-600">SIP Trunking / SIP URI</p></article><article className="rounded-2xl border border-black/10 bg-[#fbf8f1] p-6"><h3 className="font-semibold">{zh ? "可选服务商" : "Alternative providers"}</h3><p className="mt-3 text-sm leading-6 text-neutral-600">Telnyx, Vonage, {zh ? "以及其他兼容 SIP 的服务商" : "and other SIP-compatible providers"}</p></article><article className="rounded-2xl border border-black/10 bg-[#fbf8f1] p-6"><h3 className="font-semibold">{zh ? "企业接入" : "Enterprise options"}</h3><p className="mt-3 text-sm leading-6 text-neutral-600">{zh ? "已有号码、SIP Trunk、PBX 或兼容的企业电话基础设施" : "Existing numbers, SIP trunks, PBX, or compatible enterprise telephony"}</p></article></div><p className="lg:col-start-2 text-xs leading-5 text-neutral-500">{zh ? "兼容性取决于电话服务商能力与具体部署配置。" : "Compatibility depends on provider capabilities and deployment configuration."}</p></div></section>

    <section className="py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "业务结果" : "Business outcomes"}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em] sm:text-5xl">{zh ? "一次沟通，直接进入 CRM、销售与 FSM。" : "One conversation, directly connected to CRM, Sales, and FSM."}</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{outcomes.map(([title,body],i)=>{const Icon=[UserRoundCheck,ClipboardCheck,Workflow,MessageSquareText][i];return <article key={title} className="min-h-[225px] rounded-3xl border border-black/10 bg-white p-7"><Icon size={22} className="text-orange-600"/><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-neutral-600">{body}</p></article>})}</div></div></section>

    <section className="bg-neutral-950 py-16 text-white sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-300">{zh ? "商用级控制" : "Commercial-grade controls"}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em] sm:text-5xl">{zh ? "自动化可以很快，但业务动作必须准确、受控、可追踪。" : "Automation can be fast, but business actions must remain accurate, controlled, and traceable."}</h2></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{controls.map(([title,body])=><article key={title} className="min-h-[210px] rounded-2xl border border-white/10 bg-white/5 p-6"><ShieldCheck size={22} className="text-orange-300"/><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-neutral-400">{body}</p></article>)}</div></div></section>

    <section className="py-16 sm:py-24"><div className="mx-auto grid max-w-7xl gap-6 px-5 sm:px-6 md:grid-cols-2 lg:grid-cols-4 lg:px-10">{c.cards.map(([title,body],i)=>{const Icon=icons[i];return <article key={title} className="min-h-[210px] rounded-2xl border border-black/10 bg-white p-6"><Icon size={22} className="text-orange-600"/><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-neutral-600">{body}</p></article>})}</div></section>

    <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-6 sm:pb-24 lg:px-10"><div className="flex flex-col justify-between gap-8 rounded-[28px] border border-black/10 bg-white p-8 sm:p-12 lg:flex-row lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "语音接单试点" : "Voice intake pilot"}</p><h2 className="mt-4 max-w-3xl font-serif text-3xl leading-tight tracking-[-.035em] sm:text-4xl">{zh ? "从一条电话号码和一个明确工单流程开始。" : "Start with one phone number and one explicit work-order workflow."}</h2><p className="mt-4 max-w-2xl leading-7 text-neutral-600">{zh ? "验证接通率、信息完整度、人工录入减少、工单准确率与后续跟进。" : "Validate answer rate, data completeness, reduced manual entry, work-order accuracy, and follow-up discipline."}</p></div><Link href="/pilot" className="inline-flex min-h-12 shrink-0 items-center gap-2 rounded-full bg-neutral-950 px-6 font-semibold text-white">{c.cta}<ArrowRight size={18}/></Link></div></section>
    <MarketingFooter />
  </main>;
}
