"use client";

import Link from "next/link";
import { ArrowRight, ClipboardCheck, MessageSquareText, PhoneCall, ShieldCheck, UserRoundCheck, Workflow } from "lucide-react";
import { MarketingFooter } from "@/components/marketing-footer";
import { MarketingHeader } from "@/components/marketing-header";
import { useI18n } from "@/i18n/locale-provider";
import { marketingCopy } from "@/i18n/marketing-copy";

export default function VoicePage() {
  const { locale } = useI18n();
  const c = marketingCopy[locale].voice;
  const zh = locale === "zh";
  const icons = [PhoneCall, MessageSquareText, Workflow, ShieldCheck];
  const outcomes = zh
    ? [["识别客户与意图", "关联已有客户、服务地址、设备与历史记录，减少重复建档。"], ["结构化采集", "提取服务类型、问题描述、紧急程度、时间偏好与关键业务字段。"], ["生成业务动作", "创建线索、客户、工单、上门任务、跟进事项或人工接管任务。"], ["持续跟进", "发送确认、提醒、状态通知，并将每次沟通写回同一业务记录。"]]
    : [["Identify customer and intent", "Match existing customers, sites, assets, and history to reduce duplicate records."], ["Capture structured details", "Extract service type, problem, urgency, preferred time, and required business fields."], ["Create business actions", "Create leads, customers, work orders, visits, follow-up tasks, or human handoff tasks."], ["Continue the follow-up", "Send confirmations, reminders, and status updates while every interaction returns to the same record."]];
  const controls = zh ? [["确认与复述", "关键地址、时间、价格与承诺在创建业务动作前进行确认。"], ["幂等与去重", "重复呼叫、重试和服务商回调不会生成重复工单。"], ["人工接管", "低置信度、投诉、敏感或超出范围的对话即时转人工。"], ["审计与可见性", "录音、转写、提取字段、指令与结果保持关联和可追踪。"]] : [["Confirmation and read-back", "Critical addresses, times, prices, and commitments are confirmed before business actions are created."], ["Idempotency and deduplication", "Repeated calls, retries, and provider callbacks do not create duplicate work."], ["Human handoff", "Low-confidence, sensitive, complaint, or out-of-scope conversations transfer to a person."], ["Audit and visibility", "Recordings, transcripts, extracted fields, commands, and outcomes remain linked and traceable."]];

  return <main className="min-h-screen bg-[#fbf8f1] text-neutral-950"><MarketingHeader />
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 sm:py-24 lg:px-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{c.eyebrow}</p><h1 className="mt-6 max-w-5xl font-serif text-5xl leading-[1.02] tracking-[-.045em] sm:text-7xl">{c.title}</h1><p className="mt-8 max-w-3xl text-lg leading-8 text-neutral-600">{c.subtitle}</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/pilot" className="inline-flex items-center gap-2 rounded-full bg-neutral-950 px-6 py-3 font-semibold text-white">{c.cta}<ArrowRight size={18}/></Link><Link href="/solutions" className="inline-flex rounded-full border border-black/15 bg-white px-6 py-3 font-semibold">{zh ? "查看行业场景" : "Explore Solutions"}</Link></div></section>

    <section className="border-y border-black/10 bg-white py-20"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "从对话到执行" : "Conversation to execution"}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em] sm:text-5xl">{zh ? "电话不是孤立记录，而是业务流程的入口。" : "A call is not an isolated record. It is the start of an operating workflow."}</h2></div><div className="mt-12 grid gap-3 md:grid-cols-3 lg:grid-cols-6">{c.steps.map((step,index)=><div key={step} className="rounded-2xl border border-black/10 bg-[#fbf8f1] p-5"><span className="text-xs font-semibold text-orange-600">0{index+1}</span><p className="mt-7 font-semibold">{step}</p></div>)}</div></div></section>

    <section className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "业务结果" : "Business outcomes"}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em] sm:text-5xl">{zh ? "一次沟通，直接进入 CRM、销售与 FSM。" : "One conversation, directly connected to CRM, Sales, and FSM."}</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{outcomes.map(([title,body],i)=>{const Icon=[UserRoundCheck,ClipboardCheck,Workflow,MessageSquareText][i];return <article key={title} className="rounded-3xl border border-black/10 bg-white p-7"><Icon size={22} className="text-orange-600"/><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-neutral-600">{body}</p></article>})}</div></div></section>

    <section className="bg-neutral-950 py-20 text-white sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-300">{zh ? "商用级控制" : "Commercial-grade controls"}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em] sm:text-5xl">{zh ? "自动化可以很快，但业务动作必须准确、受控、可追踪。" : "Automation can be fast, but business actions must remain accurate, controlled, and traceable."}</h2></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{controls.map(([title,body])=><article key={title} className="rounded-2xl border border-white/10 bg-white/5 p-6"><ShieldCheck size={22} className="text-orange-300"/><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-neutral-400">{body}</p></article>)}</div></div></section>

    <section className="py-20 sm:py-24"><div className="mx-auto grid max-w-7xl gap-6 px-5 sm:px-6 md:grid-cols-2 lg:grid-cols-4 lg:px-10">{c.cards.map(([title,body],i)=>{const Icon=icons[i];return <article key={title} className="rounded-2xl border border-black/10 bg-white p-6"><Icon size={22} className="text-orange-600"/><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-neutral-600">{body}</p></article>})}</div></section>

    <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-6 sm:pb-24 lg:px-10"><div className="flex flex-col justify-between gap-8 rounded-[28px] border border-black/10 bg-white p-8 sm:p-12 lg:flex-row lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "语音接单试点" : "Voice intake pilot"}</p><h2 className="mt-4 max-w-3xl font-serif text-4xl tracking-[-.035em]">{zh ? "从一条电话号码和一个明确工单流程开始。" : "Start with one phone number and one explicit work-order workflow."}</h2><p className="mt-4 max-w-2xl leading-7 text-neutral-600">{zh ? "验证接通率、信息完整度、人工录入减少、工单准确率与后续跟进。" : "Validate answer rate, data completeness, reduced manual entry, work-order accuracy, and follow-up discipline."}</p></div><Link href="/pilot" className="inline-flex shrink-0 items-center gap-2 rounded-full bg-neutral-950 px-6 py-3 font-semibold text-white">{c.cta}<ArrowRight size={18}/></Link></div></section>
    <MarketingFooter />
  </main>;
}