"use client";

import { LocaleLink } from "@/components/LocaleLink";
import { ArrowRight, BookOpen, Cpu, GitBranch, Layers3, ShieldCheck, Sparkles } from "lucide-react";
import { MarketingFooter } from "@/components/marketing-footer";
import { MarketingHeader } from "@/components/marketing-header";
import { useI18n } from "@/i18n/locale-provider";
import { agentRuntimeArticles } from "@/content/agent-runtime-articles";

export default function ResourcesPage() {
  const { locale } = useI18n();
  const zh = locale === "zh";
  const runtimeArticles = Object.values(agentRuntimeArticles[locale]);
  const featured = runtimeArticles.find((article) => article.featured)!;
  const groups = [
    { key: "runtime", title: zh ? "可信 Agent Runtime" : "Governed Agent Runtime", body: zh ? "企业 Agent 所需的权限、业务事实、审计、审批和稳定执行。" : "Permissions, business truth, audit, approval, and reliable execution for enterprise Agents." },
    { key: "efficiency", title: zh ? "Agent 执行效率" : "Agent Execution Efficiency", body: zh ? "通过稳定业务能力减少重复上下文、代码生成、测试和修复。" : "Reduce repeated context, code generation, testing, and repair through stable business capabilities." },
    { key: "architecture", title: zh ? "Runory 架构" : "Runory Architecture", body: zh ? "了解 MCP、Skills、SDK、指令、流程与扩展如何组成受治理执行层。" : "See how MCP, Skills, SDKs, commands, workflows, and extensions form a governed execution layer." },
  ] as const;

  const existing = zh ? [
    { slug: "external-agents-for-sme-software", category: "战略", title: "为什么外部超级 Agent 将成为 SME 软件的新范式", summary: "超级 Agent 与受治理业务运行时，将重塑中小企业使用软件的方式。" },
    { slug: "agent-native-field-service", category: "战略", title: "什么是真正的 Agent-native 现场服务软件", summary: "为什么 Agent 应成为操作界面，而业务系统仍然是受治理的事实来源。" },
    { slug: "crm-sales-fsm-operating-loop", category: "产品", title: "CRM + 销售 + FSM：服务企业的一体化运营闭环", summary: "客户获取、销售转化与现场服务不应是割裂系统。" },
    { slug: "voice-intake-to-work-order", category: "运营", title: "从电话到工单：避免重复录入", summary: "将语音和消息对话转化为 CRM、销售与 FSM 执行。" },
    { slug: "fsm-pilot-in-1-2-weeks", category: "实施", title: "如何在 1–2 周内启动 FSM 试点", summary: "通过聚焦流程、标准模块和 Agent 辅助配置快速验证价值。" },
  ] : [
    { slug: "external-agents-for-sme-software", category: "Strategy", title: "Why External Agents Are the Future of SME Software", summary: "How Super Agents and governed business runtimes will reshape SME software." },
    { slug: "agent-native-field-service", category: "Strategy", title: "What Agent-native field service software actually means", summary: "Why the Agent should be the operating interface while the runtime remains the source of truth." },
    { slug: "crm-sales-fsm-operating-loop", category: "Product", title: "CRM + Sales + FSM: One Operating Loop", summary: "Why customer acquisition, sales execution, and field operations should work as one loop." },
    { slug: "voice-intake-to-work-order", category: "Operations", title: "From phone call to work order without duplicate entry", summary: "Convert conversations into connected CRM, Sales, and FSM execution." },
    { slug: "fsm-pilot-in-1-2-weeks", category: "Implementation", title: "How to Launch an FSM Pilot in 1–2 Weeks", summary: "A focused approach to proving value with reusable modules and Agent-assisted configuration." },
  ];

  const links = zh ? [[BookOpen, "文档", "实施指南、架构与运营参考。", "/docs"], [Layers3, "Packs 与模块", "可复用业务能力与目录结构。", "/packs"], [GitBranch, "开源", "Runtime、SDK、工具与仓库版本。", "/open-source"]] : [[BookOpen, "Documentation", "Implementation guides, architecture, and operational references.", "/docs"], [Layers3, "Packs & Modules", "Reusable business capabilities and catalog structure.", "/packs"], [GitBranch, "Open Source", "Runtime, SDK, tooling, and repository releases.", "/open-source"]];

  return <main className="min-h-screen bg-[#fbf8f1] text-neutral-950"><MarketingHeader />
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 sm:py-24 lg:px-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "观点与研究" : "Ideas & Research"}</p><h1 className="mt-5 max-w-5xl font-serif text-5xl leading-[1.03] tracking-[-.045em] sm:text-7xl">{zh ? "面向下一代企业软件的观点。" : "Ideas for the next generation of enterprise software."}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-neutral-600">{zh ? "研究受治理 Agent 执行、业务运行时架构、AI 运营效率，以及服务企业的未来。" : "Research on governed Agent execution, business runtime architecture, AI operating efficiency, and the future of service operations."}</p></section>

    <section className="border-y border-black/10 bg-white py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><LocaleLink href={`/resources/${featured.slug}`} className="group grid gap-8 overflow-hidden rounded-[28px] bg-neutral-950 p-7 text-white sm:p-10 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><span className="text-xs font-semibold uppercase tracking-[.16em] text-orange-300">{zh ? "重点研究" : "Featured research"}</span><h2 className="mt-5 max-w-4xl font-serif text-4xl leading-tight tracking-[-.035em] sm:text-5xl">{featured.title}</h2><p className="mt-5 max-w-2xl leading-7 text-neutral-300">{featured.description}</p><span className="mt-8 inline-flex items-center gap-2 font-semibold">{zh ? "阅读文章" : "Read article"}<ArrowRight size={18} className="transition group-hover:translate-x-1" /></span></div><div className="rounded-2xl border border-white/10 bg-white/5 p-6"><div className="space-y-4 text-sm"><div className="rounded-xl border border-white/10 p-4">Vibe-coded application</div><div className="pl-5 text-orange-300">↓ {zh ? "生产化鸿沟" : "Productionization gap"}</div><div className="rounded-xl border border-orange-300/40 bg-orange-300/10 p-4">Governed business runtime</div><div className="pl-5 text-orange-300">↓</div><div className="rounded-xl border border-white/10 p-4">Reliable business operation</div></div></div></LocaleLink></div></section>

    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 sm:py-24 lg:px-10"><div className="grid gap-5 md:grid-cols-2"><LocaleLink href="/resources/agent-token-efficiency" className="group rounded-[24px] border border-black/10 bg-white p-7 sm:p-8"><Sparkles size={24} className="text-orange-600" /><p className="mt-7 text-sm font-semibold uppercase tracking-[.16em] text-orange-600">{zh ? "经济价值" : "Economic value"}</p><h2 className="mt-4 font-serif text-3xl tracking-[-.03em] sm:text-4xl">{zh ? "更高效的 Agent 执行" : "More efficient Agent execution"}</h2><p className="mt-4 max-w-xl leading-7 text-neutral-600">{zh ? "让 Agent 调用稳定业务能力，而不是反复读取仓库、生成代码、测试和修复。" : "Let Agents call stable business capabilities instead of repeatedly reading repositories, generating code, testing, and repairing."}</p><span className="mt-7 inline-flex items-center gap-2 font-semibold">{zh ? "了解 10× 效率目标" : "Explore the 10× efficiency target"}<ArrowRight size={17} className="transition group-hover:translate-x-1" /></span></LocaleLink><LocaleLink href="/resources/governed-agent-runtime" className="group rounded-[24px] border border-black/10 bg-orange-50 p-7 sm:p-8"><ShieldCheck size={24} className="text-orange-600" /><p className="mt-7 text-sm font-semibold uppercase tracking-[.16em] text-orange-600">{zh ? "企业可信度" : "Enterprise trust"}</p><h2 className="mt-4 font-serif text-3xl tracking-[-.03em] sm:text-4xl">{zh ? "默认受治理的业务执行" : "Governed business execution by default"}</h2><p className="mt-4 max-w-xl leading-7 text-neutral-600">{zh ? "每一次 Agent 操作都经过身份、权限、契约、校验、事务、审计和恢复。" : "Every Agent action passes through identity, permissions, contracts, validation, transactions, audit, and recovery."}</p><span className="mt-7 inline-flex items-center gap-2 font-semibold">{zh ? "了解可信运行时" : "Explore the governed runtime"}<ArrowRight size={17} className="transition group-hover:translate-x-1" /></span></LocaleLink></div></section>

    {groups.map((group) => { const articles = runtimeArticles.filter((article) => article.theme === group.key); const Icon = group.key === "runtime" ? ShieldCheck : group.key === "efficiency" ? Cpu : Layers3; return <section key={group.key} className="border-t border-black/10 py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><div><Icon size={24} className="text-orange-600" /><h2 className="mt-5 font-serif text-4xl tracking-[-.035em]">{group.title}</h2><p className="mt-4 max-w-md leading-7 text-neutral-600">{group.body}</p></div><div className="grid gap-4 md:grid-cols-2">{articles.map((article) => <LocaleLink key={article.slug} href={`/resources/${article.slug}`} className="group rounded-2xl border border-black/10 bg-white p-6"><span className="text-xs font-semibold uppercase tracking-[.14em] text-orange-600">{article.category}</span><h3 className="mt-4 text-xl font-semibold leading-7">{article.title}</h3><p className="mt-3 text-sm leading-6 text-neutral-600">{article.description}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold">{zh ? "阅读文章" : "Read article"}<ArrowRight size={15} className="transition group-hover:translate-x-1" /></span></LocaleLink>)}</div></div></div></section>; })}

    <section className="border-y border-black/10 bg-white py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "现场服务与实施" : "Field service & implementation"}</p><h2 className="mt-4 max-w-3xl font-serif text-4xl tracking-[-.035em]">{zh ? "把行业观点连接到真实运营。" : "Connect the category to real operations."}</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{existing.map((article) => <LocaleLink key={article.slug} href={`/resources/${article.slug}`} className="group rounded-2xl border border-black/10 bg-[#fbf8f1] p-6"><span className="text-xs font-semibold uppercase tracking-[.15em] text-orange-600">{article.category}</span><h3 className="mt-5 text-xl font-semibold leading-7">{article.title}</h3><p className="mt-3 text-sm leading-6 text-neutral-600">{article.summary}</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-semibold">{zh ? "阅读文章" : "Read article"}<ArrowRight size={16} className="transition group-hover:translate-x-1" /></span></LocaleLink>)}</div></div></section>

    <section className="mx-auto grid max-w-7xl gap-5 px-5 py-16 sm:px-6 sm:py-20 md:grid-cols-3 lg:px-10">{links.map(([Icon, title, body, href]) => <LocaleLink key={String(title)} href={href as string} className="rounded-2xl border border-black/10 bg-white p-6"><Icon size={22} className="text-orange-600" /><h2 className="mt-5 text-lg font-semibold">{title as string}</h2><p className="mt-3 text-sm leading-6 text-neutral-600">{body as string}</p></LocaleLink>)}</section>
    <MarketingFooter /></main>;
}
