"use client";

import { LocaleLink } from "@/components/LocaleLink";
import { ArrowRight, Gauge, ShieldCheck } from "lucide-react";
import { useI18n } from "@/i18n/locale-provider";

export function AgentRuntimePositioning() {
  const { locale } = useI18n();
  const zh = locale === "zh";

  return <section className="border-t border-black/10 bg-white py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-10"><div className="max-w-4xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "企业 AI 缺失的一层" : "The missing layer for enterprise AI"}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em] text-neutral-950 sm:text-5xl">{zh ? "更少的 Agent 开销，更可信的业务执行。" : "Less Agent overhead. More trustworthy business execution."}</h2><p className="mt-5 max-w-3xl text-base leading-7 text-neutral-600">{zh ? "Runory 让外部 Agent 调用稳定业务能力，而不是反复重建软件；同时以权限、契约、事务、审计和恢复保护真实企业运营。" : "Runory lets external Agents call stable business capabilities instead of repeatedly reconstructing software, while permissions, contracts, transactions, audit, and recovery protect real operations."}</p></div><div className="mt-10 grid gap-5 md:grid-cols-2"><LocaleLink href="/resources/agent-token-efficiency" className="group rounded-[24px] border border-black/10 bg-[#fbf8f1] p-7"><Gauge size={24} className="text-orange-600" /><p className="mt-7 text-sm font-semibold uppercase tracking-[.16em] text-orange-600">{zh ? "Agent Efficiency" : "Agent Efficiency"}</p><h3 className="mt-4 font-serif text-3xl tracking-[-.03em]">{zh ? "目标：数量级降低执行开销" : "Target order-of-magnitude lower execution overhead"}</h3><p className="mt-4 leading-7 text-neutral-600">{zh ? "通过能力发现、命名指令、结构化结果和元数据配置，减少上下文加载、代码生成、测试与修复。" : "Use capability discovery, named commands, structured results, and metadata configuration to reduce context loading, code generation, testing, and repair."}</p><span className="mt-7 inline-flex items-center gap-2 font-semibold">{zh ? "了解效率模型" : "Explore the efficiency model"}<ArrowRight size={17} className="transition group-hover:translate-x-1" /></span></LocaleLink><LocaleLink href="/resources/governed-agent-runtime" className="group rounded-[24px] border border-orange-200 bg-orange-50 p-7"><ShieldCheck size={24} className="text-orange-600" /><p className="mt-7 text-sm font-semibold uppercase tracking-[.16em] text-orange-600">{zh ? "Governed Runtime" : "Governed Runtime"}</p><h3 className="mt-4 font-serif text-3xl tracking-[-.03em]">{zh ? "可信、稳定、企业级的 Agent 运营" : "Trusted, stable, enterprise-grade Agent operations"}</h3><p className="mt-4 leading-7 text-neutral-600">{zh ? "每个操作都进入统一身份、权限、校验、事务、审批、审计与回滚路径。" : "Every operation enters one identity, permission, validation, transaction, approval, audit, and rollback path."}</p><span className="mt-7 inline-flex items-center gap-2 font-semibold">{zh ? "了解可信运行时" : "Explore the governed runtime"}<ArrowRight size={17} className="transition group-hover:translate-x-1" /></span></LocaleLink></div><LocaleLink href="/resources/vibe-coding-to-governed-business-systems" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-neutral-700">{zh ? "从 Vibe Coding 到可信企业业务系统" : "From Vibe Coding to Governed Business Systems"}<ArrowRight size={16} /></LocaleLink></div></section>;
}
