"use client";

import Link from "next/link";
import { ArrowRight, Boxes, Braces, CloudCog, Database, KeyRound, ShieldCheck } from "lucide-react";
import { MarketingFooter } from "@/components/marketing-footer";
import { MarketingHeader } from "@/components/marketing-header";
import { useI18n } from "@/i18n/locale-provider";

export default function PlatformPage() {
  const { locale } = useI18n();
  const zh = locale === "zh";
  const layers = zh ? [["SaaS 基础层", "身份、工作空间、多租户、成员与云端运营。"], ["Runory Runtime", "元数据组合、指令、流程、权限、扩展与集成。"], ["Runory 业务层", "CRM、销售、FSM、语音接单、支付与运营状态。"]] : [["SaaS Foundation", "Identity, workspace, tenancy, membership, and cloud operations."], ["Runory Runtime", "Metadata composition, commands, workflows, permissions, extensions, and integrations."], ["Runory Business", "CRM, Sales, FSM, Voice Intake, payments, and operational business state."]];
  const cards = zh ? [["模块、Pack 与扩展", "安装可复用业务能力，并在不分叉 Core 的前提下适配每个工作空间。"], ["元数据驱动组合", "对象、字段、表单、视图、流程、权限与工具组合成有效运行模型。"], ["受治理指令", "所有写操作都经过校验、权限、风险、确认、执行与审计。"], ["MCP、Skills 与 SDK", "向 Codex、ChatGPT、Claude、Cursor、Trae 与企业 Agent 暴露清晰、版本化能力。"], ["Cloud-to-Local 基础", "统一的 libSQL/SQLite 结构保持云端与本地部署路径一致。"], ["可靠集成", "Outbox、幂等、重放、Webhook、服务商适配与可见的失败处理。"]] : [["Modules, Packs & Extensions", "Install reusable business capabilities and adapt each workspace without forking Core."], ["Metadata-driven composition", "Objects, fields, forms, views, workflows, permissions, and tools compose into one effective runtime model."], ["Governed commands", "All writes pass through validation, permission, risk, confirmation, execution, and audit."], ["MCP, Skills & SDK", "Expose clear, versioned capabilities to Codex, ChatGPT, Claude, Cursor, Trae, and enterprise Agents."], ["Cloud-to-local foundation", "A consistent libSQL/SQLite-oriented structure keeps cloud and local deployment paths aligned."], ["Reliable integrations", "Outbox, idempotency, replay, webhooks, provider adapters, and visible failure handling."]];
  const icons = [Boxes, Braces, ShieldCheck, KeyRound, Database, CloudCog];
  return <main className="min-h-screen bg-[#fbf8f1] text-neutral-950"><MarketingHeader /><section className="mx-auto max-w-7xl px-6 py-20 lg:px-10 lg:py-28"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "Runory 平台" : "Runory Platform"}</p><h1 className="mt-6 max-w-4xl font-serif text-5xl leading-[1.02] tracking-[-.045em] sm:text-7xl">{zh ? "为受治理的 Agent 执行而构建的轻量业务运行时。" : "A lightweight business runtime built for governed Agent execution."}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-neutral-600">{zh ? "外部 Agent 提供智能与编排，Runory 提供业务结构、权限、确定性指令、状态与审计。" : "External Agents provide intelligence and orchestration. Runory provides business structure, permissions, deterministic commands, state, and audit."}</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/docs" className="inline-flex items-center gap-2 rounded-full bg-neutral-950 px-6 py-3 font-semibold text-white">{zh ? "查看资源" : "Explore Resources"} <ArrowRight size={18} /></Link><Link href="/agent" className="inline-flex items-center rounded-full border border-black/15 bg-white px-6 py-3 font-semibold">{zh ? "Agent 接口" : "Agent Interface"}</Link></div></section><section className="border-y border-black/10 bg-white py-20"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="grid gap-4 md:grid-cols-3">{layers.map(([title, body], index) => <div key={title} className={`rounded-2xl border p-6 ${index === 1 ? "border-orange-300 bg-orange-50" : "border-black/10 bg-[#fbf8f1]"}`}><span className="text-xs font-semibold text-orange-600">0{index + 1}</span><h2 className="mt-8 text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-neutral-600">{body}</p></div>)}</div></div></section><section className="py-24"><div className="mx-auto grid max-w-7xl gap-6 px-6 md:grid-cols-2 lg:grid-cols-3 lg:px-10">{cards.map(([title, body], i) => { const Icon = icons[i]; return <article key={title} className="rounded-2xl border border-black/10 bg-white p-6"><Icon size={22} className="text-orange-600" /><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-neutral-600">{body}</p></article>; })}</div></section><MarketingFooter /></main>;
}
