"use client";

import Link from "next/link";
import { ArrowRight, Boxes, Braces, CloudCog, Database, Gauge, KeyRound, ShieldCheck } from "lucide-react";
import { MarketingFooter } from "@/components/marketing-footer";
import { MarketingHeader } from "@/components/marketing-header";
import { useI18n } from "@/i18n/locale-provider";

export default function PlatformPage() {
  const { locale } = useI18n();
  const zh = locale === "zh";
  const layers = zh ? [["SaaS 基础层", "身份、工作空间、多租户、成员、计费与云端运营。"], ["Runory Runtime", "元数据组合、指令、流程、权限、扩展、审计与集成。"], ["Runory 业务层", "CRM、销售、FSM、语音接单、收款与持续运营状态。"]] : [["SaaS Foundation", "Identity, workspace, tenancy, membership, billing, and cloud operations."], ["Runory Runtime", "Metadata composition, commands, workflows, permissions, extensions, audit, and integrations."], ["Runory Business", "CRM, Sales, FSM, Voice Intake, payments, and continuous operational state."]];
  const cards = zh ? [["模块、Pack 与扩展", "安装可复用业务能力，并在不分叉 Core 的前提下适配每个工作空间。"], ["元数据驱动组合", "对象、字段、表单、视图、流程、权限与工具组合成有效运行模型。"], ["受治理指令", "所有写操作都经过校验、权限、风险、确认、执行与审计。"], ["MCP、Skills 与 SDK", "向 Codex、ChatGPT、Claude、Cursor、Trae 与企业 Agent 暴露清晰、版本化能力。"], ["Cloud-to-Local 基础", "统一的数据与运行时契约，为云端、私有与本地部署保留一致路径。"], ["可靠集成", "Outbox、幂等、重放、Webhook、服务商适配与可见的失败处理。"]] : [["Modules, Packs & Extensions", "Install reusable business capabilities and adapt each workspace without forking Core."], ["Metadata-driven composition", "Objects, fields, forms, views, workflows, permissions, and tools compose into one effective runtime model."], ["Governed commands", "All writes pass through validation, permission, risk, confirmation, execution, and audit."], ["MCP, Skills & SDK", "Expose clear, versioned capabilities to Codex, ChatGPT, Claude, Cursor, Trae, and enterprise Agents."], ["Cloud-to-local foundation", "A consistent data and runtime contract preserves aligned cloud, private, and local deployment paths."], ["Reliable integrations", "Outbox, idempotency, replay, webhooks, provider adapters, and visible failure handling."]];
  const commandFlow = zh ? ["请求来源", "能力发现", "指令网关", "数据与规则校验", "权限与风险检查", "业务执行", "审计与事件"] : ["Request source", "Capability discovery", "Command gateway", "Schema & rule validation", "Permission & risk check", "Business execution", "Audit & events"];
  const principles = zh ? [["确定性执行", "Agent 负责理解和规划，Runory 负责把已确认意图转化为一致、可验证的业务状态变更。"], ["统一权限边界", "人员、Agent、工具和自动化共享同一套角色、权限和作用域模型。"], ["可观测自动化", "计划任务、条件动作、重试、升级和人工接管都保留清晰状态与审计轨迹。"], ["可持续演进", "官方 Pack、行业 Pack 和 Workspace Extension 分层管理，避免客户定制破坏产品升级。"]] : [["Deterministic execution", "Agents interpret and plan. Runory turns confirmed intent into consistent, validated business-state changes."], ["One permission boundary", "People, Agents, tools, and automations share the same role, permission, and scope model."], ["Observable automation", "Schedules, conditions, retries, escalation, and human takeover retain visible state and audit trails."], ["Sustainable evolution", "Official Packs, industry Packs, and Workspace Extensions stay separated so adaptation does not break upgrades."]];
  const icons = [Boxes, Braces, ShieldCheck, KeyRound, Database, CloudCog];

  return <main className="min-h-screen bg-[#fbf8f1] text-neutral-950"><MarketingHeader />
    <section className="mx-auto max-w-7xl px-6 py-20 lg:px-10 lg:py-28"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "Runory 平台" : "Runory Platform"}</p><h1 className="mt-6 max-w-4xl font-serif text-5xl leading-[1.02] tracking-[-.045em] sm:text-7xl">{zh ? "为受治理的 Agent 执行而构建的轻量业务运行时。" : "A lightweight business runtime built for governed Agent execution."}</h1><p className="mt-8 max-w-3xl text-lg leading-8 text-neutral-600">{zh ? "外部 Agent 提供智能与编排，Runory 提供业务结构、权限、确定性指令、状态、集成与审计。" : "External Agents provide intelligence and orchestration. Runory provides business structure, permissions, deterministic commands, state, integrations, and audit."}</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/resources" className="inline-flex items-center gap-2 rounded-full bg-neutral-950 px-6 py-3 font-semibold text-white">{zh ? "查看观点与研究" : "Explore Ideas & Research"} <ArrowRight size={18} /></Link><Link href="/agent" className="inline-flex items-center rounded-full border border-black/15 bg-white px-6 py-3 font-semibold">{zh ? "Agent 接口" : "Agent Interface"}</Link></div></section>

    <section className="border-y border-black/10 bg-white py-20"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="grid gap-5 md:grid-cols-2"><article className="rounded-[24px] border border-black/10 bg-[#fbf8f1] p-7"><Gauge size={24} className="text-orange-600" /><p className="mt-7 text-sm font-semibold uppercase tracking-[.16em] text-orange-600">{zh ? "Agent Efficiency Layer" : "Agent Efficiency Layer"}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em]">{zh ? "让 Agent 调用能力，而不是反复重建软件。" : "Let Agents call capabilities instead of reconstructing software."}</h2><p className="mt-5 leading-7 text-neutral-600">{zh ? "能力发现、紧凑 Schema、命名指令、结构化结果和元数据配置，共同减少代码仓库上下文、生成与修复循环。" : "Capability discovery, compact schemas, named commands, structured results, and metadata configuration reduce repository context, generation, and repair loops."}</p><Link href="/resources/agent-token-efficiency" className="mt-7 inline-flex items-center gap-2 font-semibold">{zh ? "了解 10× 效率目标" : "Explore the 10× efficiency target"}<ArrowRight size={17} /></Link></article><article className="rounded-[24px] border border-orange-200 bg-orange-50 p-7"><ShieldCheck size={24} className="text-orange-600" /><p className="mt-7 text-sm font-semibold uppercase tracking-[.16em] text-orange-600">{zh ? "Governed Business Runtime" : "Governed Business Runtime"}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.035em]">{zh ? "把开放式智能转化为可信企业执行。" : "Turn open-ended intelligence into trusted enterprise execution."}</h2><p className="mt-5 leading-7 text-neutral-600">{zh ? "身份、授权、指令契约、校验、事务、流程、审计、回滚与权威状态由 Runory 运行时统一负责。" : "Identity, authorization, command contracts, validation, transactions, workflows, audit, rollback, and authoritative state remain controlled by the Runory runtime."}</p><Link href="/resources/governed-agent-runtime" className="mt-7 inline-flex items-center gap-2 font-semibold">{zh ? "了解可信运行时" : "Explore the governed runtime"}<ArrowRight size={17} /></Link></article></div></div></section>

    <section className="py-20"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="grid gap-4 md:grid-cols-3">{layers.map(([title, body], index) => <div key={title} className={`rounded-2xl border p-6 ${index === 1 ? "border-orange-300 bg-orange-50" : "border-black/10 bg-white"}`}><span className="text-xs font-semibold text-orange-600">0{index + 1}</span><h2 className="mt-8 text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-neutral-600">{body}</p></div>)}</div></div></section>
    <section className="border-y border-black/10 bg-white py-20 sm:py-24"><div className="mx-auto max-w-7xl px-6 lg:px-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "受治理执行路径" : "Governed execution path"}</p><h2 className="mt-4 max-w-4xl font-serif text-4xl tracking-[-.035em] sm:text-5xl">{zh ? "开放式 Agent 意图，进入可验证的业务指令。" : "Open-ended Agent intent becomes validated business commands."}</h2><div className="mt-10 grid gap-3 md:grid-cols-7">{commandFlow.map((item, index) => <div key={item} className="rounded-2xl border border-black/10 bg-[#fbf8f1] p-5"><span className="text-xs font-semibold text-orange-600">0{index + 1}</span><p className="mt-6 text-sm font-semibold leading-6">{item}</p></div>)}</div></div></section>
    <section className="bg-neutral-950 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-5 px-6 md:grid-cols-2 lg:px-10">{principles.map(([title, body]) => <article key={title} className="rounded-2xl border border-white/10 bg-white/5 p-7"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-neutral-400">{body}</p></article>)}</div></section>
    <section className="py-24"><div className="mx-auto grid max-w-7xl gap-6 px-6 md:grid-cols-2 lg:grid-cols-3 lg:px-10">{cards.map(([title, body], i) => { const Icon = icons[i]; return <article key={title} className="rounded-2xl border border-black/10 bg-white p-6"><Icon size={22} className="text-orange-600" /><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-neutral-600">{body}</p></article>; })}</div></section>
    <section className="mx-auto max-w-7xl px-6 pb-24 lg:px-10"><div className="flex flex-col items-start justify-between gap-6 rounded-3xl bg-orange-50 p-8 sm:flex-row sm:items-center sm:p-10"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-orange-600">{zh ? "落地方式" : "Adoption path"}</p><h2 className="mt-3 max-w-3xl font-serif text-3xl tracking-[-.03em] sm:text-4xl">{zh ? "从一个 Pack 和一条关键流程开始，再逐步扩展。" : "Start with one Pack and one priority workflow, then expand deliberately."}</h2></div><Link href="/pilot" className="inline-flex shrink-0 items-center gap-2 rounded-full bg-neutral-950 px-6 py-3 font-semibold text-white">{zh ? "启动试点" : "Start a Pilot"}<ArrowRight size={18}/></Link></div></section>
    <MarketingFooter /></main>;
}
